-- Script was generated by Devart Entity Developer, Version 5.0.28.0
-- Script date 1/25/2013 5:53:47 PM
-- Target Server: SQLite
-- Server Version: 3.7

-- 
-- Creating a table "main".Albums 
-- 
CREATE TABLE "main".Albums (
   Id INTEGER PRIMARY KEY AUTOINCREMENT,
   Title TEXT NOT NULL
);

-- 
-- Creating a table "main".Artists 
-- 
CREATE TABLE "main".Artists (
   Name TEXT NOT NULL,
   CONSTRAINT PK_Artists PRIMARY KEY (Name)
);

-- 
-- Creating a table "main".Tracks 
-- 
CREATE TABLE "main".Tracks (
   Path TEXT NOT NULL,
   Title TEXT,
   Album_Id INTEGER,
   CONSTRAINT PK_Tracks PRIMARY KEY (Path),
   CONSTRAINT FK_Tracks_Album FOREIGN KEY (Album_Id) REFERENCES Albums (Id)
);

-- 
-- Creating a table "main".Albums_Artists 
-- 
CREATE TABLE "main".Albums_Artists (
   Artists_Name TEXT NOT NULL,
   Albums_Id INTEGER NOT NULL,
   CONSTRAINT PK_Albums_Artists PRIMARY KEY (Artists_Name, Albums_Id),
   CONSTRAINT FK_Albums_Artists_Artists FOREIGN KEY (Artists_Name) REFERENCES Artists (Name),
   CONSTRAINT FK_Albums_Artists_Albums FOREIGN KEY (Albums_Id) REFERENCES Albums (Id)
);

-- 
-- Creating a table "main".Tracks_Artists 
-- 
CREATE TABLE "main".Tracks_Artists (
   Artists_Name TEXT NOT NULL,
   Tracks_Path TEXT NOT NULL,
   CONSTRAINT PK_Tracks_Artists PRIMARY KEY (Artists_Name, Tracks_Path),
   CONSTRAINT FK_Tracks_Artists_Artists FOREIGN KEY (Artists_Name) REFERENCES Artists (Name),
   CONSTRAINT FK_Tracks_Artists_Tracks FOREIGN KEY (Tracks_Path) REFERENCES Tracks (Path)
);

